/**
 * Template-based fallback quiz, used when the offline pack can't be
 * generated by Gemini (no API key, free-tier quota exhausted, network
 * down, etc.). Builds up to 10 simple questions by reading structured
 * fields off the itinerary — no AI required, no network required, no
 * destination-specific copy. The kid still gets text + SFX even when
 * the fancy generator is offline.
 *
 * **Question philosophy** — every template is about one of three
 * things: a real *place* the family is visiting, a real *attraction*
 * (its description, its town, its tag), or a real *Italian word /
 * phrase* the day teaches. Meta-trip filler ("how many stops does
 * this day have?", "what day of the week is day 2?") is intentionally
 * absent — kids tune out instantly on questions about the data
 * structure of their own holiday.
 *
 * Each template:
 *   - takes the day + the rest of the itinerary as input,
 *   - returns a single `QuizQuestion` *only if* it has enough data
 *     to ask a meaningful question (otherwise returns null and the
 *     selector skips it),
 *   - sources its distractors from OTHER attractions / words / towns
 *     in the trip so wrong answers stay plausibly trip-flavored
 *     (the kid is choosing between four real Italian places, not
 *     between Saturnia and Madagascar).
 *
 * The selector then runs all templates, drops the nulls, deduplicates
 * by question text, and trims to the requested count. If we still
 * can't fill the count we just return what we got — the orchestrator
 * treats any non-empty fallback as playable.
 */

import { itinerary } from "../../data/itinerary";
import { attractions, getAttraction } from "../../data/attractions";
import { localizeDay, localizePoi } from "../../data/i18n";
import type {
  AttractionQuizFact,
  Day,
  ItalianWord,
  POI,
  Quiz,
  QuizQuestion
} from "../../data/types";
import type { Lang } from "../lang";
import { QUESTIONS_PER_OFFLINE_PACK } from "./generateQuiz";

const OPTIONS_PER_QUESTION = 4;

/** Per-language micro-dictionary — kept inside the module so the
 *  fallback works without the React `t()` hook (the module runs
 *  inside the orchestrator's startQuiz which is plain logic). Keep
 *  any new copy in sync with `dict.ts` if/when the React UI starts
 *  surfacing it. */
const COPY = {
  en: {
    correct: ["Bravissimo!", "Spot on!", "Nailed it!", "Esatto!", "Mamma mia, yes!"],
    wrong: ["Close one!", "Almost!", "Not quite —", "Oof, nope —", "Ah, the answer is"],
    /** Friendly category labels for attraction tags, used to make
     *  questions like "Which of these is great for water adventures?". */
    tag: {
      water: "splashy water adventures",
      extreme: "thrills and adrenaline",
      nature: "nature walks and forests",
      culture: "old stories and history",
      family: "easy family fun",
      food: "tasting local food",
      view: "breathtaking views",
      cave: "exploring caves",
      village: "wandering an ancient village"
    } as Record<string, string>
  },
  he: {
    correct: ["ברביסימו!", "בדיוק!", "מצוין!", "אֶזָאטוֹ!", "מאמא מיה, כן!"],
    wrong: ["קרוב!", "כמעט!", "לא ממש —", "אופ, לא —", "התשובה היא"],
    tag: {
      water: "הרפתקאות מים מרעננות",
      extreme: "ריגושים ואדרנלין",
      nature: "טבע ויערות",
      culture: "סיפורים והיסטוריה",
      family: "כיף משפחתי קליל",
      food: "טעימות אוכל מקומי",
      view: "נופים עוצרי נשימה",
      cave: "חקר מערות",
      village: "טיול בכפר עתיק"
    } as Record<string, string>
  }
} as const;

function pickReactions(
  lang: Lang,
  rng: () => number
): { reactionCorrect: string; reactionWrong: string } {
  const c = COPY[lang];
  const correct = c.correct[Math.floor(rng() * c.correct.length)];
  const wrong = c.wrong[Math.floor(rng() * c.wrong.length)];
  return { reactionCorrect: correct, reactionWrong: wrong };
}

/** Tiny seeded RNG so the same `(day, lang)` combo always produces
 *  the same fallback quiz — kid replaying gets the same set, no
 *  flicker, no surprises. mulberry32 is good enough for shuffles
 *  and 4-option picks; we don't need cryptographic strength here. */
function mulberry32(seed: number): () => number {
  let s = seed >>> 0;
  return function () {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = s;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffleInPlace<T>(arr: T[], rng: () => number): T[] {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

/** Pick `n` distractors from `pool`, skipping anything that matches
 *  `correct` (case-insensitive) and any duplicates. Returns fewer
 *  than `n` if the pool is too small — the template caller treats
 *  that as a "skip me" signal. */
function pickDistractors(
  pool: string[],
  correct: string,
  n: number,
  rng: () => number
): string[] {
  const seen = new Set<string>([correct.trim().toLowerCase()]);
  const candidates: string[] = [];
  for (const raw of pool) {
    const v = raw?.trim();
    if (!v) continue;
    const k = v.toLowerCase();
    if (seen.has(k)) continue;
    seen.add(k);
    candidates.push(v);
  }
  shuffleInPlace(candidates, rng);
  return candidates.slice(0, n);
}

/** Wrap a question + correct answer + distractors into a real
 *  `QuizQuestion`, randomizing the slot the correct option sits in
 *  so the kid can't just tap the same letter every time. Returns
 *  null if we don't have enough distractors to make 4 options. */
function buildQ(opts: {
  lang: Lang;
  question: string;
  correct: string;
  distractors: string[];
  rng: () => number;
}): QuizQuestion | null {
  if (opts.distractors.length < OPTIONS_PER_QUESTION - 1) return null;

  const distractors = opts.distractors.slice(0, OPTIONS_PER_QUESTION - 1);
  const correctSlot = Math.floor(opts.rng() * OPTIONS_PER_QUESTION);
  const options: string[] = [];
  let dIdx = 0;
  for (let i = 0; i < OPTIONS_PER_QUESTION; i++) {
    if (i === correctSlot) {
      options.push(opts.correct);
    } else {
      options.push(distractors[dIdx++]);
    }
  }

  const reactions = pickReactions(opts.lang, opts.rng);
  return {
    question: opts.question,
    options,
    correctIndex: correctSlot,
    reactionCorrect: reactions.reactionCorrect,
    reactionWrong: `${reactions.reactionWrong} ${opts.correct}`
  };
}


/* ------------------------------------------------------------------ */
/* Greek-culture wildcard bank                                          */
/* ------------------------------------------------------------------ */

/** A small bilingual bank of kid-friendly "general Greece" facts —
 *  flag, mythology, food, the Olympics, geography. Used by `tplGreekCulture`
 *  as a controlled wildcard sprinkled into the offline pack so the
 *  deck doesn't feel repetitive on attraction-thin days. The pack is
 *  still primarily about today's attractions; the selector caps how
 *  many of these can fire (see `CULTURE_BUDGET` in `buildFallbackQuiz`).
 *  Keep facts at 8-year-old reading level — no politics, no booze,
 *  no scary detail. */
const GREEK_CULTURE_FACTS: Record<Lang, AttractionQuizFact[]> = {
  en: [
    {
      question: "What colours are on the Greek flag?",
      correctAnswer: "Blue and white",
      distractors: [
        "Red, white, and blue",
        "Green, white, and red",
        "Yellow and black"
      ]
    },
    {
      question: "In ancient Greek myths, who was the king of all the gods?",
      correctAnswer: "Zeus",
      distractors: ["Poseidon", "Hades", "Apollo"]
    },
    {
      question: "The Ancient Olympic Games started in Greece. About how long ago?",
      correctAnswer: "Almost 3,000 years ago",
      distractors: ["100 years ago", "500 years ago", "10,000 years ago"]
    },
    {
      question: "What is the capital city of Greece?",
      correctAnswer: "Athens",
      distractors: ["Thessaloniki", "Sparta", "Delphi"]
    },
    {
      question: "In ancient times, people travelled to Delphi to ask questions of a famous fortune-teller. What was she called?",
      correctAnswer: "The Oracle",
      distractors: ["The Sphinx", "The Muse", "The Titan"]
    },
    {
      question: "Which of these foods is a classic Greek dish?",
      correctAnswer: "Souvlaki (grilled meat on a skewer)",
      distractors: ["Sushi", "Tacos", "Pretzels"]
    },
    {
      question: "The Greek alphabet gave its letters to a lot of math and science symbols. Which Greek letter is used for 'pi' in math?",
      correctAnswer: "π",
      distractors: ["Ω", "λ", "β"]
    },
    {
      question: "Greece has thousands of islands, but where is most of our road trip actually happening?",
      correctAnswer: "On the mainland — no islands or ferries this time",
      distractors: [
        "Only on Crete",
        "Only on Santorini",
        "We're visiting every island"
      ]
    },
    {
      question: "What is the name of the sweet, flaky dessert made of filo pastry, walnuts and honey syrup, famous all over Greece?",
      correctAnswer: "Baklava",
      distractors: ["Loukoumades", "Tiramisu", "Churros"]
    },
    {
      question: "The Ancient Greeks built huge stone temples for their gods. What is the most famous ancient temple, sitting on a hill above Athens?",
      correctAnswer: "The Parthenon, on the Acropolis",
      distractors: ["The Colosseum", "The Eiffel Tower", "The Pyramids"]
    },
    {
      question: "Which Greek hero was famous for his twelve incredibly hard labours, like fighting a lion and cleaning giant stables?",
      correctAnswer: "Hercules (Heracles)",
      distractors: ["Odysseus", "Achilles", "Perseus"]
    },
    {
      question: "According to legend, King Leonidas and 300 Spartan warriors made their famous last stand against a huge army at which mountain pass — a place we're actually driving through?",
      correctAnswer: "Thermopylae",
      distractors: ["Meteora", "Delphi", "Marathon"]
    },
    {
      question: "The monasteries of Meteora are famous for being built in a very unusual place. Where?",
      correctAnswer: "On top of tall rock pillars",
      distractors: ["Under the sea", "Inside a volcano", "In a desert"]
    },
    {
      question: "What Greek word do you shout when you're celebrating, especially when someone smashes a plate at a party?",
      correctAnswer: "Opa!",
      distractors: ["Ciao!", "Olé!", "Skål!"]
    },
    {
      question: "The city of Nafplio, on our trip, used to be ruled by which seafaring European power, and still has their fortress walls?",
      correctAnswer: "The Venetians",
      distractors: ["The Vikings", "The Romans", "The English"]
    }
  ],
  he: [
    {
      question: "אילו צבעים יש בדגל היווני?",
      correctAnswer: "כחול ולבן",
      distractors: ["אדום, לבן וכחול", "ירוק, לבן ואדום", "צהוב ושחור"]
    },
    {
      question: "במיתולוגיה היוונית העתיקה, מי היה מלך כל האלים?",
      correctAnswer: "זאוס",
      distractors: ["פוסידון", "האדס", "אפולו"]
    },
    {
      question: "המשחקים האולימפיים העתיקים התחילו ביוון. לפני כמה זמן בערך?",
      correctAnswer: "כמעט לפני 3,000 שנה",
      distractors: ["לפני 100 שנה", "לפני 500 שנה", "לפני 10,000 שנה"]
    },
    {
      question: "מהי עיר הבירה של יוון?",
      correctAnswer: "אתונה",
      distractors: ["תסלוניקי", "ספרטה", "דלפי"]
    },
    {
      question: "בזמנים עתיקים, אנשים נסעו לדלפי כדי לשאול שאלות מגברת ידועה שחזתה עתידות. איך קראו לה?",
      correctAnswer: "האורקל",
      distractors: ["הספינקס", "המוזה", "הטיטאן"]
    },
    {
      question: "איזה מהמאכלים הבאים הוא מנה יוונית קלאסית?",
      correctAnswer: "סובלאקי (בשר צלוי על שיפוד)",
      distractors: ["סושי", "טאקו", "בייגלה"]
    },
    {
      question: "האלפבית היווני נתן את האותיות שלו לסמלים רבים במתמטיקה ובמדע. איזו אות יוונית משמשת ל'פאי' במתמטיקה?",
      correctAnswer: "π",
      distractors: ["Ω", "λ", "β"]
    },
    {
      question: "ביוון יש אלפי איים, אבל איפה קורה רוב הטיול שלנו בפועל?",
      correctAnswer: "ביבשת - בלי איים ובלי מעבורות הפעם",
      distractors: ["רק בכרתים", "רק בסנטוריני", "אנחנו מבקרים בכל אי"]
    },
    {
      question: "מה שמו של הקינוח המתוק והפריך העשוי מבצק פילו, אגוזי מלך וסירופ דבש, המפורסם בכל יוון?",
      correctAnswer: "בקלאווה",
      distractors: ["לוקומדס", "טירמיסו", "צ'ורוס"]
    },
    {
      question: "היוונים הקדמונים בנו מקדשי אבן ענקיים לאלים שלהם. מהו המקדש העתיק המפורסם ביותר, היושב על גבעה מעל אתונה?",
      correctAnswer: "הפרתנון, על האקרופוליס",
      distractors: ["הקולוסיאום", "מגדל אייפל", "הפירמידות"]
    },
    {
      question: "איזה גיבור יווני היה מפורסם בזכות שנים עשר מעשי גבורה קשים במיוחד, כמו קרב באריה וניקוי אורוות ענקיות?",
      correctAnswer: "הרקולס (הרקלס)",
      distractors: ["אודיסאוס", "אכילס", "פרסאוס"]
    },
    {
      question: "לפי האגדה, המלך לאונידס ו-300 לוחמים ספרטנים עמדו בקרב האחרון המפורסם שלהם מול צבא ענק באיזה מעבר הרים - מקום שאנחנו בעצם נוסעים דרכו?",
      correctAnswer: "תרמופילאי",
      distractors: ["מטאורה", "דלפי", "מרתון"]
    },
    {
      question: "המנזרים של מטאורה מפורסמים בזכות מיקום מאוד יוצא דופן. איפה?",
      correctAnswer: "על גבי עמודי סלע גבוהים",
      distractors: ["מתחת לים", "בתוך הר געש", "במדבר"]
    },
    {
      question: "איזו מילה יוונית צועקים כשחוגגים, במיוחד כשמישהו שובר צלחת במסיבה?",
      correctAnswer: "אופה!",
      distractors: ["צ'או!", "אולה!", "סקול!"]
    },
    {
      question: "עיר נאפפליו, בטיול שלנו, נשלטה בעבר על ידי איזו מעצמה ימית אירופית, ועדיין יש בה את חומות המבצר שלהם?",
      correctAnswer: "הוונציאנים",
      distractors: ["הוויקינגים", "הרומאים", "האנגלים"]
    }
  ]
};

/* ------------------------------------------------------------------ */
/* Templates — ALL substantive (places / attractions / Italian)        */
/* ------------------------------------------------------------------ */

interface TemplateContext {
  lang: Lang;
  rng: () => number;
  day: Day;
  /** Other days, already localized. */
  otherDays: Day[];
  /** All attractions, already localized — used as a wide distractor
   *  pool. */
  allAttractions: POI[];
  /** Just the attractions the family visits *today*, localized.
   *  Templates use this for the "correct" answer when the question
   *  is grounded in the day's plan. */
  todaysAttractions: POI[];
}

/** Q: what does the Greek word X mean? */
function tplWordMeaning(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, lang, rng } = ctx;
  const words: ItalianWord[] = day.italianWords ?? [];
  if (words.length === 0) return null;
  const w = words[Math.floor(rng() * words.length)];
  if (!w?.meaning) return null;
  const otherMeanings = otherDays
    .flatMap(d => (d.italianWords ?? []).map(o => o.meaning))
    .filter(Boolean);
  const distractors = pickDistractors(
    otherMeanings,
    w.meaning,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `מה המשמעות של המילה היוונית "${w.word}"?`
        : `What does the Greek word "${w.word}" mean?`,
    correct: w.meaning,
    distractors,
    rng
  });
}

/** Q: how do you say [meaning] in Greek? — reverse of tplWordMeaning. */
function tplWordReverse(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, lang, rng } = ctx;
  const words: ItalianWord[] = day.italianWords ?? [];
  if (words.length === 0) return null;
  const w = words[Math.floor(rng() * words.length)];
  if (!w?.word || !w?.meaning) return null;
  const otherWords = otherDays
    .flatMap(d => (d.italianWords ?? []).map(o => o.word))
    .filter(Boolean);
  const distractors = pickDistractors(
    otherWords,
    w.word,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `איך אומרים "${w.meaning}" ביוונית?`
        : `How do you say "${w.meaning}" in Greek?`,
    correct: w.word,
    distractors,
    rng
  });
}

/** Q: which Greek phrase means "[example translation]"? */
function tplPhraseExample(ctx: TemplateContext): QuizQuestion | null {
  const { day, otherDays, lang, rng } = ctx;
  const phrases = (day.italianWords ?? []).filter(
    w => w.example && w.exampleMeaning
  );
  if (phrases.length === 0) return null;
  const w = phrases[Math.floor(rng() * phrases.length)];
  if (!w.example || !w.exampleMeaning) return null;
  const otherExamples = otherDays
    .flatMap(d => (d.italianWords ?? []).map(o => o.example).filter(Boolean))
    .filter((e): e is string => Boolean(e) && e !== w.example);
  const distractors = pickDistractors(
    otherExamples,
    w.example,
    OPTIONS_PER_QUESTION - 1,
    rng
  );
  return buildQ({
    lang,
    question:
      lang === "he"
        ? `איזה משפט ביוונית אומר "${w.exampleMeaning}"?`
        : `Which Greek phrase means "${w.exampleMeaning}"?`,
    correct: w.example,
    distractors,
    rng
  });
}

/** Q: a kid-friendly general "Greece" fact pulled from the
 *  `GREEK_CULTURE_FACTS` bank above (flag colours, mythology,
 *  the Oracle of Delphi, the Olympics, souvlaki, …). The selector
 *  caps how many of these are allowed per pack (see `CULTURE_BUDGET`)
 *  — the deck stays primarily about the day's actual attractions,
 *  with one or two of these sprinkled in for variety on
 *  attraction-thin days. */
function tplGreekCulture(ctx: TemplateContext): QuizQuestion | null {
  const { lang, rng } = ctx;
  const bank = GREEK_CULTURE_FACTS[lang];
  if (!bank || bank.length === 0) return null;
  const fact = bank[Math.floor(rng() * bank.length)];
  return buildQ({
    lang,
    question: fact.question,
    correct: fact.correctAnswer,
    distractors: fact.distractors,
    rng
  });
}

/** Q: a hand-curated story / legend / signature-detail question
 *  about an attraction the family visits today. Pulls from the
 *  attraction's `quizFacts` array (authored alongside its
 *  description in `attractions.ts` + the HE overlay) — the
 *  template doesn't generate the question from text, it just lifts
 *  the curated fact and randomizes which option the correct answer
 *  lands in. This is the template that gets us the "Devil's Bridge
 *  → dog" class of question, and it's deliberately FIRST in the
 *  template list so it dominates the offline pack on any day with
 *  story-rich attractions. */
function tplAttractionStory(ctx: TemplateContext): QuizQuestion | null {
  const { todaysAttractions, lang, rng } = ctx;
  // Build a flat (attraction, fact) catalog so we pick uniformly
  // across facts, not across attractions — otherwise an attraction
  // with 4 facts gets the same chance as one with 1 fact and we
  // end up overweighting the latter on multi-pass runs.
  type Pair = { att: POI; fact: AttractionQuizFact };
  const catalog: Pair[] = [];
  for (const att of todaysAttractions) {
    if (!att.quizFacts) continue;
    for (const fact of att.quizFacts) {
      if (!fact.question || !fact.correctAnswer) continue;
      if (!fact.distractors || fact.distractors.length < OPTIONS_PER_QUESTION - 1) continue;
      catalog.push({ att, fact });
    }
  }
  if (catalog.length === 0) return null;

  const pick = catalog[Math.floor(rng() * catalog.length)];
  // Distractor pool: the curated wrong answers from the SAME fact.
  // We don't blend in distractors from other facts because the
  // author already tuned these to be plausible-but-clearly-wrong
  // for THIS specific question (e.g. "A dog" vs "A cat / goat /
  // chicken" — mixing in "Saturnia" would obviously give it away).
  return buildQ({
    lang,
    question: pick.fact.question,
    correct: pick.fact.correctAnswer,
    distractors: pick.fact.distractors,
    rng
  });
}


const WORD_TEMPLATES: Array<(ctx: TemplateContext) => QuizQuestion | null> = [
  tplWordMeaning,
  tplWordReverse,
  tplPhraseExample
];

const TEMPLATES: Array<(ctx: TemplateContext) => QuizQuestion | null> = [
  // Curated story trivia first — when the attraction author has
  // written quizFacts for today's stops, these are the highest-
  // quality questions in the deck.
  tplAttractionStory
];

/* ------------------------------------------------------------------ */
/* Public entry point                                                  */
/* ------------------------------------------------------------------ */

/**
 * Build a fallback `Quiz` of up to `count` questions for `(day, lang)`,
 * deterministic per `(day, lang, count)`. Throws only if there is no
 * itinerary entry for the day at all (the orchestrator surfaces that
 * as a real error). If templates can't fill the requested count, the
 * returned quiz is shorter — the orchestrator treats any non-empty
 * fallback as playable.
 *
 * Each template can fire MULTIPLE times in one quiz (we re-run the
 * same set in shuffled order after the first pass, picking different
 * source items via the RNG) so a 10-question pack genuinely covers
 * 10 facts about the day instead of the 9 we'd get from one-shot
 * templates.
 */
export function buildFallbackQuiz(
  dayNumber: number,
  lang: Lang,
  count: number = QUESTIONS_PER_OFFLINE_PACK
): Quiz {
  const rawDay = itinerary.find(d => d.dayNumber === dayNumber);
  if (!rawDay) {
    throw new Error(`No itinerary entry for day ${dayNumber}`);
  }

  const day = lang === "he" ? localizeDay(rawDay, "he") : rawDay;
  const otherDays = itinerary
    .filter(d => d.dayNumber !== dayNumber)
    .map(d => (lang === "he" ? localizeDay(d, "he") : d));

  const pastDays = itinerary.filter(d => d.dayNumber <= dayNumber);
  const pastAttractionIds = new Set(
    pastDays.flatMap(d => d.activities.map(a => a.attractionId).filter(Boolean))
  );

  const allAttractions = attractions
    .filter(a => pastAttractionIds.has(a.id))
    .map(a => (lang === "he" ? localizePoi(a, "he") : a));

  // Today's attractions: pull every activity with an `attractionId`
  // and look it up. This gives us proper rich POIs (with shortDesc,
  // tags, address) instead of the bare activity titles, which is
  // what makes the questions actually about *places*.
  const todaysAttractions: POI[] = day.activities
    .map(a => (a.attractionId ? getAttraction(a.attractionId) : null))
    .filter((a): a is POI => Boolean(a))
    .map(a => (lang === "he" ? localizePoi(a, "he") : a));

  // Seed: day + lang + count. Picks a stable but unique RNG stream
  // for each combination.
  const seed = dayNumber * 1009 + (lang === "he" ? 7 : 13) + count * 31;
  const rng = mulberry32(seed);

  const ctx: TemplateContext = {
    lang,
    rng,
    day,
    otherDays,
    allAttractions,
    todaysAttractions
  };

  const collected: QuizQuestion[] = [];
  const seen = new Set<string>();
  const tryAdd = (q: QuizQuestion | null) => {
    if (!q) return;
    if (collected.length >= count) return;
    const key = q.question.trim().toLowerCase();
    if (seen.has(key)) return;
    seen.add(key);
    collected.push(q);
  };

  // PASS 1 — Words (Target 2 questions). The user explicitly requested
  // 1-2 questions about Italian words learned today.
  const MAX_WORDS = todaysAttractions.length < 2 ? 1 : 2;
  let wordsAdded = 0;
  for (let pass = 0; pass < 3 && wordsAdded < MAX_WORDS && collected.length < count; pass++) {
    const order = shuffleInPlace([...WORD_TEMPLATES.keys()], rng);
    for (const idx of order) {
      if (wordsAdded >= MAX_WORDS || collected.length >= count) break;
      const before = collected.length;
      tryAdd(WORD_TEMPLATES[idx](ctx));
      if (collected.length > before) wordsAdded++;
    }
  }

  // PASS 2 — Greek-culture wildcards (Target 4 questions, or more if few attractions).
  // The user explicitly requested 3-5 questions about general Italy
  // (flag, pizza Margherita, artists, geography). If there are very few
  // attractions today, fill the rest of the quiz with culture questions.
  const MAX_CULTURE = todaysAttractions.length < 2 ? (count - wordsAdded) : 4;
  let cultureAdded = 0;
  for (
    let i = 0;
    i < MAX_CULTURE * 4 && cultureAdded < MAX_CULTURE && collected.length < count;
    i++
  ) {
    const before = collected.length;
    tryAdd(tplGreekCulture(ctx));
    if (collected.length > before) cultureAdded++;
  }

  // PASS 3 — Curated Attraction Stories. When attractions on this day
  // have hand-authored `quizFacts`, those are the highest-quality
  // questions about the specific attractions.
  for (let i = 0; i < 10 && collected.length < count; i++) {
    tryAdd(tplAttractionStory(ctx));
  }

  // PASS 4 — fill remaining slots with the diverse generic attraction templates
  // (description, town, tag, region).
  const MAX_PASSES = 4;
  for (let pass = 0; pass < MAX_PASSES && collected.length < count; pass++) {
    const order = shuffleInPlace([...TEMPLATES.keys()], rng);
    for (const idx of order) {
      if (collected.length >= count) break;
      tryAdd(TEMPLATES[idx](ctx));
    }
  }

  // Finally, shuffle the collected questions so the different types
  // (words, culture, stories) are randomly mixed instead of clustered.
  shuffleInPlace(collected, rng);

  return {
    day: dayNumber,
    lang,
    questions: collected,
    // Marker timestamp 0 = "this is a fallback, not a real Gemini
    // generation". Anything reading the cache can distinguish if it
    // wants to (current orchestrator uses it to drive the banner).
    generatedAt: 0
  };
}
